config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  devise_for :users
  get '/users', to: 'users#index', as: 'users'
  get '/user/:id', to: 'users#show', as: 'user'
  get '/user/:id/reviews', to: 'users#reviews_list', as: 'reviews_user'
  get '/user/:id/products', to: 'users#products', as: 'products_user'

  root 'categories#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.admin? 
        can :manage, :all
        cannot :manage, Product
      else
        can [:new, :create], [Product, Review]
      end
      can :manage, Product, :user_id => user.id
    end
    can [:products, :reviews_list], User
    can [:index, :show], :all
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :title, :description, :price, presence: true
  validates :price, format: { :with => /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }

	def average_rating
		reviews.any? ? reviews.pluck(:rating).sum.to_f / reviews.count : 0
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, :rating, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products

  validates :firstname, :lastname, presence: true

  def fullname
  	"#{firstname} #{lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      redirect_to root_path, alert: exception.message
    else
      redirect_to new_user_session_path, :notice => flash[:alert] || "You must login first"
    end
  end

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :firstname << :lastname
    devise_parameter_sanitizer.for(:account_update) << :firstname << :lastname
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :index
  
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  expose(:category)
  expose(:products)
  expose(:product)
  expose_decorated(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
    @products = category.products
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    authenticate_user!
    self.product = Product.new(product_params)
    product.user_id = current_user.id
    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
  
  expose_decorated(:review)
  expose_decorated(:reviews, ancestor: :product)
  expose_decorated(:product)
  expose_decorated(:category)

  def edit
  end

  def create
    self.review = Review.new(review_params)
    review.user = current_user
    if review.save
      product.reviews << review
      redirect_to category_product_path(product.category, product), notice: 'Review was successfully created.'
    else
      render 'products/show'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_path(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
  
  expose_decorated(:users)
  expose_decorated(:user)
  expose_decorated(:reviews, ancestor: :user)

  def index
  end

  def show
  end

  def products
  end

  def reviews_list
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.haml
= simple_form_for category do |f|
  - if category.errors.any?
    .alert.alert-danger
      #error_explanation
        %h4= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
        %ul
          - category.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.input :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/categories/edit.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', categories_path, class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to 'Show', category

  %li{ role: "presentation" }
    = link_to 'Products', category_products_path(category)

  - if can? :new, Product
    %li{ role: "presentation" }
      = link_to "New Product", new_category_product_path(category)

  %li{ role: "presentation", class: "active" }
    = link_to 'Edit', "#"
    
  - if can? :delete, category
    %li{ role: "presentation" }
      = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%h3= category.name

= render 'form'

app/views/categories/index.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation", class: "active" }
    = link_to "Listing Categories", "#"

  - if can? :create, Category
    %li{ role: "presentation" }
      = link_to "New Category", new_category_path

  %li{ role: "presentation" }
    = link_to "Listing Users", users_path

%h3 Listing categories

%table.table
  %tr
    %th Name
    %th

  - categories.each do |category|
    - if can? :show, category
      %tr
        %td= category.name
        %td
          = link_to 'Show', category, class: "btn btn-info btn-xs"
          - if can? :edit, Category
            = link_to 'Edit', edit_category_path(category), class: "btn btn-warning btn-xs"
          - if can? :destroy, Category
            = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"

app/views/categories/new.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Listing Categories', categories_path

  %li{ role: "presentation", class: "active" }
    = link_to "New Category", "#"

  %li{ role: "presentation" }
    = link_to "Listing Users", users_path

%h3 New category

= render 'form'

app/views/categories/show.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', categories_path, class: 'btn btn-primary'

  %li{ role: "presentation", class: "active" }
    = link_to 'Show', "#"

  %li{ role: "presentation" }
    = link_to 'Products', category_products_path(category)

  - if can? :new, Product
    %li{ role: "presentation" }
      = link_to "New Product", new_category_product_path(category)

  - if can? :edit, category
    %li{ role: "presentation" }
      = link_to 'Edit', edit_category_path(category)
      
  - if can? :delete, category
    %li{ role: "presentation" }
      = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%h3= category.name

%p
  %b Name:
  = category.name

%p
  %b Last Products:
  - category.products.last(5).each do |product|
    = "#{product.title}, "

app/views/layouts/_flash.haml
- if flash[:notice]
  .alert.alert-success= flash[:notice]
- elsif flash[:alert]
  .alert.alert-danger= flash[:alert]
- elsif flash[:error]
  .alert.alert-danger= flash[:error]

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %title Netguru Rzeszów Workshops 2015
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand #{AppConfig.workshops_name}
        %p.navbar-text.navbar-right
          = render :file => "#{Rails.root}/app/views/devise/shared/_links.haml"
    .container-fluid
      .starter-template
        .row
          .col-lg-2
          .col-lg-8
            = render :file => "#{Rails.root}/app/views/layouts/_flash.haml"
            = yield
          .col-lg-2

app/views/products/_form.html.haml
= simple_form_for [category, product] do |f|
  - if product.errors.any?
    .alert.alert-danger
      #error_explanation
        %h4= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
        %ul
          - product.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.input :title, class: 'form-control'
  .form-group
    = f.input :description, class: 'form-control'
  .form-group
    = f.input :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/products/edit.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', category_products_path(category), class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to 'Show', category_product_path(product.category, product)

  %li{ role: "presentation", class: "active" }
    = link_to 'Edit', "#"

  - if can? :delete, product
    %li{ role: "presentation" }
      = link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%h3= product.title

= render 'form'

app/views/products/index.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', categories_path, class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to 'Show', category

  %li{ role: "presentation", class: "active" }
    = link_to 'Products', "#"

  - if can? :new, Product
    %li{ role: "presentation" }
      = link_to "New Product", new_category_product_path(category)

  - if can? :edit, category
    %li{ role: "presentation" }
      = link_to 'Edit', edit_category_path(category)
      
  - if can? :delete, category
    %li{ role: "presentation" }
      = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%h3= category.name

%table.table
  %tr
    %th Title
    %th Price
    %th


  - @products.each do |product|
    %tr
      %td= product.title
      %td= product.price
      %td
        = link_to 'Show', category_product_path(product.category, product), class: "btn btn-info btn-xs"
        - if can? :edit, product
          = link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-warning btn-xs"
        - if can? :delete, product
          = link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"

app/views/products/new.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', categories_path, class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to 'Show', category

  %li{ role: "presentation" }
    = link_to 'Products', category_products_path(category)

  %li{ role: "presentation", class: "active" }
    = link_to "New Product", "#"

  - if can? :edit, category
    %li{ role: "presentation" }
      = link_to 'Edit', edit_category_path(category)
      
  - if can? :delete, category
    %li{ role: "presentation" }
      = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

%h3= category.name

= render 'form'

app/views/products/show.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', category_products_path(category), class: 'btn btn-primary'

  %li{ role: "presentation", class: "active" }
    = link_to 'Show', "#"

  - if can? :edit, product
    %li{ role: "presentation" }
      = link_to 'Edit', edit_category_product_path(product.category, product)

  - if can? :delete, product
    %li{ role: "presentation" }
      = link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }

%h3= product.title

%p
  %b Owner:
  = product.user.fullname
%p
  %b Category
  = product.category.name
%p
  %b Title:
  = product.title
%p
  %b Description:
  = product.description
%p
  %b Average rating:
  = product.average_rating
%p
  %b Price:
  = product.price

%h3 Reviews
- if can? :create, Review
  = render 'reviews/form', locals: { product: product, category: product.category }
%p
.ul{ :class=> "list-group" }
  = render reviews

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    .alert.alert-danger
      #error_explanation
        %h4= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
        %ul
          - review.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.input :content, class: 'form-control'
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-default'

app/views/reviews/_review.html.haml
.li{ :class=> "list-group-item" }
  %span(class="badge")
    %b= review.rating
  %p= review.content
  %p
    %em= review.author

app/views/users/index.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Listing Categories', categories_path

  - if can? :create, Category
    %li{ role: "presentation" }
      = link_to "New Category", new_category_path

  %li{ role: "presentation", class: "active" }
    = link_to "Listing Users", "#"

%h3 Listing users

%table.table
  %tr
    %th First name
    %th Last name
    %th Email
    %th

  - users.each do |user|
    - if can? :show, user
      %tr
        %td= user.firstname
        %td= user.lastname
        %td= user.email
        %td
          = link_to 'Show', user_path(user), class: "btn btn-info btn-xs"

app/views/users/products.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', users_path, class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to "Show", user_path(user)

  %li{ role: "presentation", class: "active" }
    = link_to 'Products', "#"

  %li{ role: "presentation" }
    = link_to 'Last Reviews', reviews_user_path(user)

%h3= user.fullname

%p
  %b Products

%table.table
  %tr
    %th Category
    %th Title
    %th Description
    %th Price

  - user.products.each do |product|
    %tr
      %td= product.category.name
      %td= product.title
      %td= product.description
      %td= product.price

app/views/users/reviews_list.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', users_path, class: 'btn btn-primary'

  %li{ role: "presentation" }
    = link_to "Show", user_path(user)

  %li{ role: "presentation" }
    = link_to 'Products', products_user_path(user)

  %li{ role: "presentation", class: "active" }
    = link_to 'Last Reviews', "#"

%h3= user.fullname

%p
  %b Last Reviews

%table.table
  %tr
    %th Date
    %th Category
    %th Product
    %th Content
    %th Rating

  - reviews.last(5).each do |review|
    %tr
      %td= review.created_at
      %td= review.product.category.name
      %td= review.product.title
      %td= review.content
      %td= review.rating

app/views/users/show.html.haml
%ul{ :class => "nav nav-tabs" }

  %li{ role: "presentation" }
    = link_to 'Back', users_path, class: 'btn btn-primary'

  %li{ role: "presentation", class: "active" }
    = link_to "Show", "#"

  %li{ role: "presentation" }
    = link_to 'Products', products_user_path(user)

  %li{ role: "presentation" }
    = link_to 'Last Reviews', reviews_user_path(user)

%h3= user.fullname

%p
  %b First name:
  = user.firstname

%p
  %b Last name:
  = user.lastname

%p
  %b Email:
  = user.email
%p
  %b Created at:
  = user.created_at

%p
  %b Sign in count:
  = user.sign_in_count

%p
  %b Last sign in at:
  = user.last_sign_in_at